# Generated by Django 3.2.8 on 2021-10-12 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_details',
            name='address',
        ),
        migrations.AlterField(
            model_name='seller_details',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
