# Generated by Django 3.2.8 on 2021-10-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20211012_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_details',
            name='username',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
