# Generated by Django 3.2.8 on 2021-10-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='seller',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
