# Generated by Django 3.2.8 on 2021-10-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_orders_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='seller',
        ),
    ]
